-- Create the FAQ Knowledge Base table
create table if not exists faq_kb (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  keywords text, -- Optional keywords for better matching
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table faq_kb enable row level security;

-- Policy: Allow public read access (for the chat bot)
create policy "Public can view FAQs"
  on faq_kb for select
  using ( true );

-- Policy: Allow authenticated admins to insert/update/delete
-- Assuming you have an admin role or check for authenticated user
-- For simplicity in this project context, we often allow authenticated users if it's an admin-only app, 
-- or we can restrict it further.
create policy "Admins can manage FAQs"
  on faq_kb for all
  using ( auth.role() = 'authenticated' );

-- Create a text search index for better matching
-- This allows us to use plainto_tsquery or phraseto_tsquery
create index if not exists faq_kb_question_idx on faq_kb using gin(to_tsvector('indonesian', question));
